# Minimal Shiny Server config: serve our app at '/'
run_as shiny;

env SHINY_LOG_STDERR=1;

server {
  listen 3838 0.0.0.0;

  location / {
    app_dir /srv/shiny-server/app;
    directory_index off;
  }

  log_dir /var/log/shiny-server;
}
